"""add phone number

Revision ID: 949cbeb8338b
Revises: 3b8abd65aa73
Create Date: 2022-11-17 12:09:37.005693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949cbeb8338b'
down_revision = '3b8abd65aa73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
